---
Harwell:
  :preferred: ''
  :default: ''
HMGU:
  :preferred: ''
  :default: ''
ICS:
  :preferred: ''
  :default: ''
CNB:
  :preferred: ''
  :default: ''
Monterotondo:
  :preferred: ''
  :default: ''
JAX:
  :preferred: 'http://jaxmice.jax.org/list/komp_strains'
  :default: 'http://jaxmice.jax.org/list/komp_strains'
Oulu:
  :preferred: ''
  :default: ''
VETMEDUNI:
  :preferred: ''
  :default: ''
BCM:
  :preferred: 'mailto:jcrowe@bcm.tmc.edu?subject=Mutant mouse for MARKER_SYMBOL'
  :default: ''
CNRS:
  :preferred: ''
  :default: ''
APN:
  :preferred: ''
  :default: ''
TCP:
  :preferred: 'mailto:lauryl.nutter@phenogenomics.ca?subject=Mutant mouse for MARKER_SYMBOL'
  :default: 'mailto:lauryl.nutter@phenogenomics.ca?subject=Mutant mouse enquiry'
MARC:
  :preferred: ''
  :default: ''  
UCD:
  :preferred: 'http://www.komp.org/geneinfo.php?project=PROJECT_ID'
  :default: 'http://www.komp.org/'
WTSI:
  :preferred: 'mailto:mouseinterest@sanger.ac.uk?subject=Mutant mouse for MARKER_SYMBOL'
  :default: ''
EMMA:
  :preferred: 'http://www.emmanet.org/mutant_types.php?keyword=MARKER_SYMBOL'
  :default: ''
MMRRC:
  :preferred: 'http://www.mmrrc.org/catalog/StrainCatalogSearchForm.php?search_query=MARKER_SYMBOL'
  :default: ''
KOMP:
  :preferred: 'http://www.komp.org/geneinfo.php?project=PROJECT_ID'
  :default: 'http://www.komp.org/'
  
